### ISSUE TITLE
Создать функцию хэширования паролей

### ISSUE THREAD

**Issue by CruzedV** [GarageMakers/bukovki#15]
ИСПОЛЬЗОВАТЬ bcrypt - npm

**Comment by Uzhastin-Nikita** [comment]
https://overcoder.net/q/1397365/rsa-%D1%88%D0%B8%D1%84%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B4%D0%B5%D1%88%D0%B8%D1%84%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B2-typescript
